### ISSUE TITLE
Provide autoconfiguration for the handler mapping

### ISSUE THREAD

**Issue by wimdeblauwe** [BoukeNijhuis/dynamic-version-url#1]
It is possible to have your library provide autoconfiguration like this:

1. Create a Java class that is annotated with `@AutoConfiguration` and implements `WebMvcRegistrations`. Something like this:

```
@AutoConfiguration
@ConditionalOnWebApplication
public class DynamicVersionUrlMvcAutoConfiguration implements WebMvcRegistrations {

    @Override
    public RequestMappingHandlerMapping getRequestMappingHandlerMapping() {
        return new ApiVersionRequestMappingHandlerMapping("v");
    }
}
```

2. Create a file called `org.springframework.boot.autoconfigure.AutoConfiguration.imports` in `src/main/resources/META-INF/spring` with the full qualified name of your autoconfig class. See https://github.com/wimdeblauwe/htmx-spring-boot/blob/main/htmx-spring-boot/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports for an example.

I believe that is all there is to it. You probably want to make that prefix configurable via an `@ConfigurationProperties` class as well.

**Comment by BoukeNijhuis** [comment]
Fixed in version 0.0.10.
