### ISSUE TITLE
Use separate annotations?

### ISSUE THREAD

**Issue by wimdeblauwe** [BoukeNijhuis/dynamic-version-url#2]
I think it is a drawback of the library that you need to replace all your `@GetMapping` annotations with `@GetVersionMapping` annotations. If you are currently not using versions, and you want to start using this library, you need to replace all of them. I think it would be nicer if it was a separate annotation, so the usage would be:

```
@GetMapping("/a")
@VersionMapping(1)
public  String a1() {
  //...
}
```

**Comment by BoukeNijhuis** [comment]
Solved in version 0.0.11.

@wimdeblauwe Thank you for coming up with the idea.
